### PR TITLE
Updates to 2D support.

### PR DESCRIPTION
**Pull request by pjohalloran**
- 2D component naming convention.
- Vector3Toggle property.
- Removal of Behaviour2D property.

### CODE REVIEW

**Comment by GandaG** [comment]
@pjohalloran have you tested the toggle changes?

**Comment by pjohalloran** [comment]
I have with an AutomonousVehicle2D. Seems to be OK. What problem did you have with it?

**Comment by GandaG** [comment]
It was 2 months ago, I don't really remember :/ but I did revert it. Oh well, if there is some rare bug with it we'll just fix it later.

**Comment by pjohalloran** [comment]
OK.

**Pull request merged**
